version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - ./db_data:/var/lib/postgresql/data/

  backend:
    image: ghcr.io/network-inventory/ni-backend/ni-backend:latest
    environment:
      - DJANGO_SETTINGS_MODULE
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
      - NI_BASE_URL
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    depends_on:
      - db
    ports:
      - 8000:8000

  frontend:
    image: ghcr.io/network-inventory/ni-frontend/ni-frontend:latest
    environment:
      - NI_BASE_URL
    depends_on:
      - backend
    ports:
      - 80:80
